---
local:
  root_dir : <%= ENV['TRAVIS_BUILD_DIR'] %>

targets:
  - type     : "bintray"
    user     : <%= ENV['BINTRAY_SNOWPLOW_GENERIC_USER'] %>
    password : <%= ENV['BINTRAY_SNOWPLOW_GENERIC_API_KEY'] %>

packages:
  - repo     : "snowplow-generic"
    name     : "factotum-server"
    user_org : "snowplow"
    publish  : true
    override : false
    continue_on_conflict: false
    version  : <%= CMD['cat Cargo.toml | grep "^version = " | awk -v N=3 '{print $N}' | tr -d "\"" | tr -d "\n"'] %>
    build_version : <%= ENV['TRAVIS_TAG'] %>
    build_commands:
      - "cargo build --verbose --release"
    artifacts:
      - prefix : "factotum_server_"
        suffix : "<%= ENV['RM_SUFFIX'] %>"
        type   : "zip"
        binary_paths:
          - "target/release/factotum-server"